name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      skip_tests:
        description: 'Skip tests (use with caution)'
        required: false
        default: false
        type: boolean
      deploy_message:
        description: 'Deployment message'
        required: false
        default: 'Manual deployment'
        type: string

jobs:
  manual-deploy:
    name: Manual Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        if: github.event.inputs.skip_tests != 'true'
        run: |
          npm run type-check
          npm run lint
          npm run test:coverage
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          VITE_TMDB_BASE_URL: https://api.themoviedb.org/3
          VITE_TMDB_IMAGE_BASE_URL: https://image.tmdb.org/t/p
          VITE_APP_NAME: Movie Recommendation App
          VITE_APP_VERSION: 1.0.0
          
      - name: Build application
        run: npm run build
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          VITE_TMDB_BASE_URL: https://api.themoviedb.org/3
          VITE_TMDB_IMAGE_BASE_URL: https://image.tmdb.org/t/p
          VITE_APP_NAME: Movie Recommendation App
          VITE_APP_VERSION: 1.0.0
          
      - name: Deploy to Vercel
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ github.event.inputs.environment == 'production' && '--prod' || '' }}
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          VITE_TMDB_BASE_URL: https://api.themoviedb.org/3
          VITE_TMDB_IMAGE_BASE_URL: https://image.tmdb.org/t/p
          VITE_APP_NAME: Movie Recommendation App
          VITE_APP_VERSION: 1.0.0
          
      - name: Create deployment summary
        run: |
          echo "## 🚀 Manual Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Message**: ${{ github.event.inputs.deploy_message }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tests Skipped**: ${{ github.event.inputs.skip_tests }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployed by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp**: $(date -u)" >> $GITHUB_STEP_SUMMARY